# exclude SafeMath when calculating test coverage
# https://eth-brownie.readthedocs.io/en/v1.10.3/config.html#exclude_paths

networks:
    default: development
    # development:
        # gas_limit: max
        # gas_buffer: 1
        # gas_price: 0
        # max_fee: null
        # priority_fee: null
        # reverting_tx_gas_limit: max
        # default_contract_owner: true
    # - cmd: ganache-cli
    #   cmd_settings:
    #       port: 8545
    #       gas_limit: 6721975
    #       accounts: 10
    #       chain_id: 1337
    #       network_id: 1588949648
    #       evm_version: istanbul
    #       fork: null
    #       mnemonic: purse melody atom walk pelican buyer hire swamp expire left lady three
    #       block_time: 0
    #       default_balance: 100
    #       time: 2020-05-08T14:54:08+0000
    #       unlock: null
    live:
    - name: Ethereum
      networks:
      - chainid: 1
        explorer: https://api.etherscan.io/api
        host: https://eth-mainnet.alchemyapi.io/v2/$WEB3_ALCHEMY_PROJECT_ID
        id: mainnet
        name: Mainnet (Alchemy)
      - chainid: 3
        explorer: https://api-ropsten.etherscan.io/api
        host: https://ropsten.infura.io/v3/$WEB3_ALCHEMY_PROJECT_ID
        id: ropsten
        name: Ropsten (Alchemy)
      - chainid: 4
        explorer: https://api-rinkeby.etherscan.io/api
        host: https://rinkeby.infura.io/v3/$WEB3_ALCHEMY_PROJECT_ID
        id: rinkeby
        name: Rinkeby (Alchemy)
        mnemonic: ${MNEMONIC}
      - chainid: 5
        explorer: https://api-goerli.etherscan.io/api
        host: https://eth-goerli.alchemyapi.io/v2/$WEB3_ALCHEMY_PROJECT_ID
        id: goerli
        name: Goerli (Alchemy)
      - chainid: 42
        explorer: https://api-kovan.etherscan.io/api
        host: https://eth-kovan.alchemyapi.io/v2/$WEB3_ALCHEMY_PROJECT_ID
        id: kovan
        name: Kovan (Alchemy)

compiler:
    solc: 
      version: 0.8.11
      remappings:
        - "@openzeppelin=/home/loophe/brownie/open/node_modules/@openzeppelin"
        - "@chainlink=/home/loophe/brownie/open/node_modules/@chainlink"

wallets:
  from_key: ${PRIVATE_KEY}

dotenv: .env